print("NNNNNNN                                        PPPPPPPPPPPPPPPPPPPPPPPP")
print("NNNN   NNNN                       NNNN         PPPPPPPPPPPPPPPPPPPPPPPPP")
print("NNNN     NNNN                     NNNN         PPPP                   PPPP")
print("NNNN       NNNN                   NNNN         PPPP                    PPPP")
print("NNNN         NNNN                 NNNN         PPPP                    PPPP")
print("NNNN           NNNN               NNNN         PPPP                   PPPP")
print("NNNN             NNNN             NNNN         PPPPPPPPPPPPPPPPPPPPPPPPP")
print("NNNN               NNNN           NNNN         PPPPPPPPPPPPPPPPPPPPPPPP")
print("NNNN                 NNNN         NNNN         PPPP")
print("NNNN                   NNNN       NNNN         PPPP")
print("NNNN                     NNNN     NNNN         PPPP")
print("NNNN                       NNNN   NNNN         PPPP")
print("NNNN                          NNNNNNNN         PPPP")